name: water_reminder
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  kartal: ^3.5.0
  flutter_riverpod: ^2.4.5
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/color/
    - assets/lotties/

flutter_gen:
  output: lib/products/generation/
  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml
